name: gakumon_app_01
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
 

  flutter_localizations: 
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.1.0
  google_fonts: ^6.2.1
  intl: ^0.20.2

  
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true 
  image_path: "assets/images/Image.png"  
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/images/Image.png"